* <<<CP1201>>> MODERN OPERATING SYSTEMS
:properties:
:author: H Shahul Hamead, S Lakshmi Priya
:date: 28 June 2018
:end:

{{{credits}}}
|L|T|P|C|
|4|0|0|4|

** Course Objectives
- To understand the design of Operating Systems.
- To learn about the contemporary operating systems.
- To explore the design of Mobile Operating Systems.  
- To apply the knowledge of scheduling in Real-Time problems.  
- To apply the knowledge of resource handling techniques on Real-Time
  problems.

{{{unit}}}
|Unit I|Virtualization and Multiprocessor Systems|9| 
History -- Requirements -- Type 1 and Type 2 hypervisors -- Techniques
for efficient virtualization -- Microkernels -- Memory and I/O
Virtualizations -- Clouds -- Case study: Vmware -- Multiprocessors --
Multicomputers -- Distributed systems

{{{unit}}}
|Unit II|Design of Mobile OS|12| 
Android and Google -- History of Android -- Design goals --
architecture -- Linux extensions -- Dalivik -- Binder IPC -- Android
applications -- Intents -- Application sandboxes-- Security -- Process
model -- Typical system architecture -- SoC -- Memory layout and
mapping -- Development setup -- Evaluation boards

{{{unit}}}
|Unit III|Scheduling in Real-time Systems |12| 
Introduction -- Applications -- Basic model -- Characteristics of real
time system -- Safety -- Task types -- Timing constraints -- Concepts
and characteristics of types of real-time task scheduling -- Clock
driven scheduling -- Event driven scheduling -- Earliest Deadline
First -- Rate monotonic algorithm.

{{{unit}}}
|Unit IV|Resource Handling Techniques in Real-time Systems |12| 
Resource sharing -- Priority inversion -- Priority inheritance
protocol -- Highest locker protocol -- Priority ceiling protocol--
Types of priority inversions -- Important features -- Issues and task
dependencies.

{{{unit}}}
|Unit V|Operating Sytem Design|12|
The nature of the design problem -- Interface design --
implementation-- Performance -- Project management -- Trends in
Operating system design.

\hfill *Total: 60*

** Course Outcomes
After the completion of this course, students will be able to: 
- Apply various techniques related to virtualization and
  multi-processor systems for similar problems (K3).
- Describe the build of Android Operating System (K2).
- Apply scheduling problems in real time applications (K3).
- Apply resource handling problems in real time environment (K3).
- Install and work with modern OS and comprehend its practical
  design (K3).
      
** References
1. Andrew S. Tanenbaum and Herbert Bos, ``Modern Operating Systems'',
   4th Edition, Pearson, 2015 (Units 1, 2 and 5)
2. Rajib Mall, ``Real Time Systems: Theory and Practice'', Pearson,
   2007 (Units 4 and 5)
3. Karim Yaghmour, ``Embedded Android'', O-Rielly, 2013 (Unit 2)
4. Matthew Portnoy, ``Virtualization Essentials'', Wiley, 2012
5. Jerome Saltzer M. and Frans Kaashoek, ``Principles of Computer
   System Design'', 1st Edition, Elsevier, 2009
6. Joshua Drake et al, ``Android Hackers Handbook'', Wiley, 2014
7. Francis Cottet, Joelle Delacroix, et al, ``Scheduling in Real-Time
   Systems'', Wiley, 2002

