* <<<CP1202>>> INTERNET OF THINGS
:properties:
:author: V S Felix Enigo, K R Sarath Chandran
:date: 29 June 2018
:end:

{{{credits}}}
|L|T|P|C|
|3|0|2|4|

** Course Objectives
- To understand the fundamentals of Internet of Things
- To learn about the basics of IOT protocols 
- To build a small low cost embedded system using Arduino/Raspberry Pi.
- To apply the concept of Internet of Things in the real world scenario. 


{{{unit}}}
|Unit I|Introduction|9| 
M2M and IoT Technology Fundamentals -- Devices and gateways, Local and
wide area networking, Data management, Business processes in IoT,
Everything as a Service (XaaS), M2M and IoT Analytics, Knowledge
Management. IoT-An Architectural Overview -- Building an architecture,
Main design principles and needed capabilities, An IoT architecture
outline, standards considerations.

{{{unit}}}
|Unit II|IoT Reference Architecture|9| 
IoT Architecture: State of the Art -- Reference Model: Domain model --
information model --functional model -- communication model -- IoT
Reference Architecture: Functional View -- Information View --
Deployment and Operational View.

{{{unit}}}
|Unit III|IoT Protocols|9| 
Protocol Standardization for IoT -- Efforts –- M2M and WSN Protocols
-– SCADA and RFID Protocols -– Unified Data Standards -– Protocols -–
IEEE 802.15.4 -– BACNet Protocol -– Modbus -– Zigbee Architecture -–
Network layer -- 6LowPAN -- CoAP

{{{unit}}}
|Unit IV|Building IoT Systems|9|
Logical design using Python -- IoT Physical devices and Endpoints:
Basic building blocks of IoT Device -- Raspberry Pi -- Linux on
Raspberry Pi -- Interfaces -- Programming Raspberry Pi with Python --
Other IoT Platform: Arduino.

{{{unit}}}
|Unit V|Case Studeies and Real World Applications|9|
Home Automation -- Cities: Smart Parking – Environment: Weather
monitoring -- Agriculture: Smart irrigation -- Data Analytics for IoT
-- Software & Management Tools for IoT Cloud Storage Models &
Communication APIs -- Cloud for IoT -- Amazon Web Services for IoT.

\hfill *Total: 45*

Suggestive Experiments (using Arduino / Raspberry Pi Board)
1. Study of Arduino and Raspberry Pi Board
2. LED Blinking and Fading 
3. Push Button and LDR Interfacing 
4. IR and Buzzer Interfacing 
5. DC Motor Interfacing
6. Joystick Interfacing
7. Stepper Motor Interfacing
8. PIR Motion Sensor Interfacing
9. IMU Interfacing
10. Temperature and Humidity sensor interfacing
11. Application Development using Arduino / Raspberry Pi using various
    sensors (Examples: Smart parking, Smart Traffic Control)
12. Application Development by integrating Arduino and Raspberry Pi in
    Cloud Platform (Examples: Basic Home Automation, Weather
    Monitoring)

\hfill *Total: 30*

** Course Outcomes
After completion of this course, students should be able to:
- Understand the basic buiding blocks and Data  Management in Internet of Things (K2)
- Understand different IoT Architectures (K2)
- Understand various protocols for IoT  (K2)
- Implement a low cost IoT system using Arduino / Rasperry Pi  (K3)
- Implement an IoT application in cloud environment (k3)


** References
1. Jan Ho¨ ller, Vlasios Tsiatsis , Catherine Mulligan, Stamatis , Karnouskos, Stefan Avesand. David Boyle, ``From Machine-to-Machine to the Internet of Things - Introduction to a New Age of Intelligence'', Elsevier, 2014. 
2. Honbo Zhou, ``The Internet of Things in the Cloud: A Middleware Perspective '', CRC Press, 2012. 
3. Olivier Hersent, David Boswarthick, Omar Elloumi , ``The Internet of Things – Key applications and Protocols'', Wiley, 2012. 
4. Arshdeep Bahga, Vijay Madisetti, ``Internet of Things – A hands-on approach'', Universities Press, 2015.



