* <<<CP1221>>> NATURAL LANGUAGE PROCESSING
:Properties:
:author: D Thenmozhi, B Senthil Kumar
:date: 28 June 2018
:end:

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** Course Objectives
- To learn the language models.
- To understand the levels of knowledge in language processing.
- To explore text processing using Python.
- To understand the NLP applications. 

{{{unit}}}
|Unit I |Overview and Language Modeling|8| 
Origins and challenges of NLP -- Knowledge in language processing --
NLP applications; Language Modeling: Language and grammar --
Grammar-based language models -- Lexical functional grammar --
Government and binding; Statistical Language Model: N-gram model --
Smoothing techniques

{{{unit}}}
|Unit II|Word Level and Syntactic Analysis|9| 
Word Level Analysis: Regular expressions -- Survey of morphology --
Word and sentence tokenization -- Stemmer -- Word classes --
Part-of-Speech Tagging: HMM POS tagging; Syntactic Analysis:
Constituency -- Context-free grammar -- Dependency Grammar; Parsing:
Top-down -- Bottom-up -- Ambiguity -- Early algorithm -- CYK --
Probabilistic CFG -- Probabilistic CYK parsing; Tree banks

{{{unit}}}
|Unit III|Semantic Analysis And Discourse Processing |10| 
The representation of Meaning: Meaning representation -- Computational
desiderata for representation; Lexical Semantics: word senses --
relations -- WordNet; Word Sense Disambiguation: Dictionary-based --
Supervised -- Minimally-supervised -- Word Similarity: thesaurus
methods -- distributional methods; Discourse Processing: Reference
resolution -- Anaphora resolution algorithms -- Co-reference
resolution

{{{unit}}}
|Unit IV|Natural Language Processing With Python |9| 
Natural Language Toolkit (NLTK); Computing with Language: Texts and
words -- Simple statistics; Accessing Text Corpora: Brown corpus --
Reuters corpus -- Wordnet; Normalizing text -- Automatic Tagging;
Supervised Classification: Gender identification -- Feature selection
-- Document classification

{{{unit}}}
|Unit V|Machine Translation, IR And IE|9|
Machine Translation: Problems in machine translation -- Classical MT
-- Statistical MT; Information Retrieval: The vector space model --
Term weighting -- Evaluation of IR; Information Extraction: Named
entity recognition -- Relation detection and classification

\hfill *Total: 45*

** Course Outcomes
After the completion of the course, students will be able to: 
- Describe the language models (K2)
- Explain levels of knowledge in language processing (K2)
- Write Python programs for text processing (K3)
- Apply NLP techniques to MT, IR and IE systems (K3)
 
     
** References
1. Daniel Jurafsky and James H Martin, “Speech and Language Processing: An introduction to Natural Language Processing, Computational Linguistics and Speech Recognition”,2nd Edition, Prentice Hall, 2008.
2. Tanveer Siddiqui, U.S. Tiwary, “Natural Language Processing and Information Retrieval”, Oxford University Press, 2008.
3. Steven Bird, Ewan Klein, and Edward Loper, “Natural Language Processing with Python”, O’Reilly, 2009.
4. Christopher D. Manning, Hinrich Schutze, Foundations of Statistical Natural Language Processing, MIT Press, 1999.
5. Nitin Indurkhya, Fred J. Damerau, Handbook of Natural Language Processing, 2nd Edition, CRC Press, 2010.
