* CP1235 BIO-INSPIRED COMPUTING
:properties:
:author: S Saraswathi
:date: 26 June 2018
:end:

#+startup: showeall

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** Course Objectives
- To Learn bio-inspired theorem and algorithms.
- To understand foundations of complex systems and theoretical biology.
- To Understand random walk and simulated annealing. 
- To Learn genetic algorithm and differential evolution .
- To Learn swarm optimization and ant colony for feature selection.
- To understand application of various algorithms.
 
{{{unit}}}
|Unit I |Introduction|9| 
Introduction to Algorithms: Newton's method -- Optimization --
No-Free-Lunch theorems -- Nature-Inspired metaheuristics; Analysis of
Algorithms: Nature inspires algorithms -- Parameter tuning and
parameter control



{{{unit}}}
|Unit II|Random Walks and Annealing|9| 
Random Walks: Random variables -- Isotropic random walks -- Levy
distribution and flights -- Markov chains -- Step sizes and search
efficiency -- Modality and intermittent search strategy -- Importance
of randomization -- Eagle strategy; Annealing: Annealing and Boltzmann
distribution -- Parameters -- SA algorithm -- Stochastic tunnelling

{{{unit}}}
|Unit III|Genetic Algorithms and Differential Evolution|9| 
Introduction to genetic algorithms -- Role of genetic operators --
Choice of parameters -- GA variants -- Schema theorem -- Convergence
analysis; Introduction to differential evolution -- Variants -- Choice
of parameters -- Convergence analysis -- Implementation

{{{unit}}}
|Unit IV|Swarm Optimization and Firefly Algorithm|9| 
Swarm Intelligence -- PSO algorithm -- Accelerated PSO --
Implementation -- Convergence analysis -- Binary PSO; The Firefly
algorithms -- Algorithm analysis -- Implementation -- Variants; Cuckoo
behaviour -- Cuckoo search

{{{unit}}}
|Unit V| Bat Flower Pollination Ant and Bee Algorithms|9|
Echolocation of bats -- Bat algorithms -- Binary Bat algorithms --
Variants of the Bat algorithm; Flower pollination algorithms --
Multi-Objective Flower pollination algorithms -- validation and
Numerical experiments;Ant algorithms -- Bee-inspired algorithms

\hfill *Total: 45*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand principles of biologically inspired computing (K2)
- Understand random walk and simulated annealing (K2)
- Apply genetic algorithms (K3)
- Solve problems using swarm intelligence and cuckoo search (K3)
- Apply bio-inspired algorithms to solve real world problems (K3)
      
** References
1. Xin-She Yang, ``Nature Ispired Optimization Algorithm'', Elsevier
   First Edition, 2014
2. Eiben A.E., Smith, James E, ``Introduction to Evolutionary
   Computing'', Springer, 2015
3. Stephan Olariu, Albert Y. Zomaya, ``Handbook of Bioinspired
   Algorithms and Application'', Chapman & Hall/CRC, 2006
4. Dan Simon, `` Evolutionary Optimization Algorithms''. John Wiley &
   Sons, 2013
5. Helio J.C. Barbosa, ``Ant Colony Optimization - Techniques and
   Applications'', Intech, 2013
6. Yang, Cui,XIao,Gandomi,Karamanoglu ,``Swarm Intelligence and
   Bio-Inspired Computing'', Elsevier First Edition, 2013



