* SOFTWARE PROJECT MANAGEMENT
:properties:
:author:  A Chamundeeswari
:date: 27 June 2018
:end:

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objective
#+BEGIN_COMMENT
Software project management course describes the key aspects of a
managerial process in Software organization. It addresses the topics
related to project planning, estimation, and scheduling. The more
prominent software development practices, Agile and DevOps software
development is introduced in this course. The major software
activities security and risk management concerned with software
development are also covered. This course introduces the monitoring
skill and performance evaluation of the team which is very vital for
the Software project managers.
#+END_COMMENT

{{{unit}}}
|Unit I|Project Planning|9|
Project management life cycle - project evaluation and programme
management - project planning - project models : waterfall, spiral,
prototyping, incremental delivery, DSDM, agile, scrum, XP, lean
software development - process model selection.

{{{unit}}}
|Unit II|Estimation and Scheduling|9|
Effort estimation techniques - Expert judgement - FPA - FP mark II -
COSMIC- COCOMO II - cost estimation - project schedules - network
model - identifying critical activities.

{{{unit}}}
|Unit III|Agile and Devops|9|
SCRUM - organization - estimation - planning - changes in scrum - risk
in scrum - product backlog - sprint backlog - release - Identifying
Stories and Preparing to Build - DevOps: Motivation - Cloud as a
platform - Operations - Deployment Pipeline.

{{{unit}}}
|Unit IV|Security and Risk Management|9|
Cloud Information Security Objectives - Cloud Security Services -
Secure Development Practices - Risk culture - risk management
process - risk attributes - risk identiification - types of risk
analysis - responding to risk - risk tracking - risk models.

{{{unit}}}
|Unit V|Monitoring and Organizing Teams|9|
Visualizing Progress – Relationship between people and effort, Task
Set & Network - Earned Value Analysis - SCM - Managing Contracts –
Working in teams - Developing metrics on a software development
program - Evaluating performance.

\hfill *Total: 45*

** Course Outcome
#+BEGIN_COMMENT
Upon completion of the course, the student should be able to:
- Apply management skills and techniques to develop commercial software projects
- Selecting a process model for software development.
- Produce cost to manage the software development and maintenance.
- To develop a project using agile and devops software development practices
- Study the activities of security and risk in various types of software projects.
- Balancing the software development  activities to deliver a product.
- Perform the managerial process of measuring the people involved in development. 
#+END_COMMENT


** References
1. Bob Hughes, Mike Cotterell, Rajib Mall, ``Software Project
   Management'', Sixth Edition, Tata McGraw Hill, 2018.
2. Ravindranath Pandian, ``Applied Software Risk Management A Guide
   for Software Project Managers'', Auerbach Publication, 2007
3. Roger S. Pressman, ``Software Engineering - A Practitioner’s
   Approach'', Seventh Edition, Mc Graw-Hill International
   Edition, 2010.
4. Rajib Mall, ``Fundamentals of Software Engineering'', 3rd edition,
   PHI Learning Pvt. Ltd., 2009.
5. ``A Guide to the Scrum Body of Knowledge (SBOK Guide)'', 2016
   edition, SCRUMstudy, Phoenix, Arizona 85008 USA.
6. Len Bass, Ingo Weber and Liming Zhu, ``DevOps: A Software
   Architect's Perspective'', Pearson Education, 2016.
7. Ronald L. Krutz, Russell Dean Vines, ``Cloud Security - A
   comprehensive Guide to Secure Cloud Computing'', Wiley -
   India, 2010.

